//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS_Complex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Presences = new HashSet<Presences>();
        }
    
        public int EmpID { get; set; }
        public string Mobile { get; set; }
        public string AccountNumber { get; set; }
        public string Address { get; set; }
        public int UserID { get; set; }
        public int SalaryID { get; set; }
        public int GradeID { get; set; }
    
        public virtual Grades Grades { get; set; }
        public virtual Salary Salary { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presences> Presences { get; set; }
    }
}
