//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS_Complex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipments
    {
        public int EquipmentID { get; set; }
        public string EquipmentName { get; set; }
        public Nullable<decimal> EquipmentQuantity { get; set; }
        public int ObiectID { get; set; }
    
        public virtual Obiect Obiect { get; set; }
    }
}
