//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS_Complex.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRMS_DBEntities : DbContext
    {
        public HRMS_DBEntities()
            : base("name=HRMS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee_Types> Employee_Types { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Equipments> Equipments { get; set; }
        public virtual DbSet<Grades> Grades { get; set; }
        public virtual DbSet<Obiect> Obiect { get; set; }
        public virtual DbSet<Presences> Presences { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<Salary> Salary { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
