//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS_Complex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Presences
    {
        public int PresenceID { get; set; }
        public decimal InTime { get; set; }
        public decimal OutTime { get; set; }
        public System.DateTime Presence_Date { get; set; }
        public int StatusID { get; set; }
        public int EmpID { get; set; }
        public int ObiectID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Obiect Obiect { get; set; }
        public virtual Status Status { get; set; }
    }
}
