//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS_Complex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> DataProjectStart { get; set; }
        public Nullable<System.DateTime> DataProjectEnd { get; set; }
        public string Description { get; set; }
        public int ObiectID { get; set; }
    
        public virtual Obiect Obiect { get; set; }
    }
}
